### ISSUE TITLE
Investigate frontend ideas

### ISSUE THREAD

**Issue by mbottini** [PDX-Checkers/checkers#2]
We haven't covered this in class, but it seems that you know significantly more about React than I do. In general, how are we actually going to draw the board on the screen?

My very naive impression with zero frameworks is something along the lines of the following:

* It's an 8-by-8 board, so we've got 64 `div`s, each of which are either going to be red square or black square classes. Javascript can make this responsive and vary the width/height of the divs according to the size of the window.

* We place men/kings on the board by adding an additional class to the square that will hold it. CSS does the rest to place an image of the man/king on the square.

* The two standard ways of moving in online board games are click-drag-release and click-source click-target. I'm happy with just implementing one. In either case, Javascript will add or remove classes to denote pieces moving or being captured.

* A WebSocket connection will send a POST request to the server when a move is made. The frontend will then listen for the response, which will contain either a success code and the new game state, or HTTP Code 400 if the move is illegal.

* Upon moving and getting a success code, the frontend updates the game state. The WebSocket now listens for the opponent's move, and will update the state when it occurs.

* (Stretch goal) Authentication? We have our plate full with the above, but I'm interested in how we can ensure that only the two people playing the game can make moves for that particular game.

---

I'm interested in how you'd approach this with an MVVM style. I have a vague idea of how it should be done, but I'm not sure on the specifics.

**Comment by ryanclanigan** [comment]
In terms of drawing the board+pieces we could go with raw html with an id/class for each piece and then find the tile we're moving from/towards and rerender each div with the classes we want (e.g. remove piece class from div and then add a piece class to the tile we're moving to). I don't like that option because its annoying to add/remove pieces by selecting specific elements.

I think what we can do is use the coordinates of the board state to instead have react draw the divs in a loop and we can conditionally apply the correct pieces on various coordinates. See the below excerpt from this link: https://reactjsnews.com/NgRepeat-Equivalent-in-React

```
var RepeatModule = React.createClass({
  getDefaultProps: function() {
    return { items: [] }
  },
  render: function() {

    var listItems = this.props.items.map(function(item) {
      return (
        <li key="{item.name}">
          <a href="{item.link}">{item.name}</a>
        </li>
      );
    });

    return (
        <ul>
          {listItems}
        </ul>
    );
};
```

In terms of clicking/dragging and websockets I'll have to do actual research on that. I know websockets require a decent amount of frontend/backend work, but hopefully we can make it fairly simple.

**Comment by mbottini** [comment]
Since we've resolved how things are going to work, I'm closing this. Once we see our MVP, we'll make more issues if we need to modify the frontend.
